# Generated by Django 3.0.2 on 2020-05-03 12:53

import apps.main.models.users
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('job_position', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                ('avatar', models.ImageField(blank=True, max_length=256, null=True, upload_to=apps.main.models.users.avatar_upload_to, verbose_name='Аватар')),
                ('supervisor_id', models.IntegerField(default=0, verbose_name='Id начальника')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
