# Generated by Django 3.0.2 on 2020-05-04 21:11

import apps.main.models.users
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Диалог',
                'verbose_name_plural': 'Диалоги',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('job_position', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                ('avatar', models.ImageField(blank=True, max_length=256, null=True, upload_to=apps.main.models.users.avatar_upload_to, verbose_name='Аватар')),
                ('supervisor_id', models.IntegerField(default=0, verbose_name='Id начальника')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('story_points', models.IntegerField(blank=True, default=1, verbose_name='Стори поинты')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('end_date', models.DateTimeField(verbose_name='Время создания')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_executor', to='main.Profile', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('media', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, size=10)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialog_related', to='main.Dialog', verbose_name='Диалог')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_recipient', to='main.Profile', verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to='main.Profile', verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.AddField(
            model_name='dialog',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialog_recipient', to='main.Profile', verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='dialog',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialog_sender', to='main.Profile', verbose_name='Отправитель'),
        ),
    ]
