# Generated by Django 3.0.2 on 2020-05-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время окончания'),
        ),
    ]
