# Generated by Django 3.0.2 on 2020-05-03 14:11

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('recipient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_recipient', to='main.Profile', verbose_name='Получатель')),
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_sender', to='main.Profile', verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Диалог',
                'verbose_name_plural': 'Диалоги',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('media', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=10)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('dialogue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_related', to='main.Dialogue', verbose_name='Диалог')),
                ('recipient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_recipient', to='main.Profile', verbose_name='Получатель')),
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to='main.Profile', verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
