# Generated by Django 3.0.2 on 2020-05-04 22:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200504_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='buttons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, default=[], size=10),
            preserve_default=False,
        ),
    ]
