# Generated by Django 3.0.2 on 2020-05-03 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dialogue_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_recipient', to='main.Profile', verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_sender', to='main.Profile', verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='message',
            name='dialogue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_related', to='main.Dialogue', verbose_name='Диалог'),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_recipient', to='main.Profile', verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to='main.Profile', verbose_name='Отправитель'),
        ),
    ]
