# Generated by Django 3.0.2 on 2020-05-03 18:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200503_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, size=10),
        ),
    ]
