# Generated by Django 3.0.2 on 2020-05-04 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200503_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('story_points', models.IntegerField(blank=True, default=1, verbose_name='Стори поинты')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('end_date', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_executor', to='main.Profile', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
